name: healthclick_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  http: 1.3.0
  cached_network_image: ^3.4.0
  flutter_stripe: ^11.5.0
  laravel_echo: ^1.0.0-beta.1
  socket_io_client: ^2.0.0
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.5
  google_sign_in: ^6.1.6
  geolocator: ^11.0.0
  getwidget: ^6.0.0
  google_maps_flutter: ^2.12.1
  provider: ^6.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  custom_refresh_indicator: ^4.0.1
  

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/Saude.png
    - assets/google.png
    - assets/background.jpg
    - assets/dif.jpg
    - assets/back.png
    - assets/back1.jpg
    - assets/back2.jpg
    - assets/back3.jpg
    - assets/click.png
    
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/click.png" # caminho da sua imagem
  android: true
  ios: true